package cpsc326;

enum TokenType {
    EOF, AND, LEFT_PAREN, RIGHT_PAREN, RIGHT_BRACE, 
    LEFT_BRACE, COMMA, DOT,PLUS,MINUS, 
    STAR,SLASH,SEMICOLON, BANG, BANG_EQUAL,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, IDENTIFIER,
    STRING, NUMBER, FALSE, FOR, FUN, 
    IF, NIL, OR, PRINT, RETURN, 
    THIS, STRUCT, TRUE, VAR, WHILE,
    EQUAL, EQUAL_EQUAL, ELSE, 
}
